rahulray11/github-fest-2021

Weather App/config.ini, Weather App/weather.py
=> GUI weather App

subtraction.md
=> created subtraction file using java

amazon price tracker/amazon price tracker.py
This script can be used to track the price of any amazon product .
=> Added Amazon price tracker

Rock_Paper_Scissor Game/script.js
Fixed some indentation, swapped var to const and updated functions to use arrow functions instead. General style improvements.
=> General Improvements to RPS Script

DIctionaryApp/app.js, DIctionaryApp/index.html, DIctionaryApp/style.css
added feature in dictionary app
=> feat: click on synonym to navigate to synonym's definition

currency-convertor/README.md, currency-convertor/app.js, currency-convertor/index.html, currency-convertor/style.css
It is a simple currency converter using **exchange rate API**
=> Currency converter

Linear Search/linearsearch.py
=> Added linearsearch.py

Calculator/calculator.py
Created a new folder Calculator and added calculator.py program.
Please accept the pull request and add `hacktobefest-accepted` label.
Thank you.
=> Added a new program

MergeSort/mergeSort.cpp
I have added two algorithm One for Merge Sort which prints every steps of Merge Sort and another Job Scheduling algorithm
=> Added Merge Sort and Job Scheduling Algorithm -

form/index.html, form/script.js
I formatted the html and js to make it easier to read. I've also updated the validate function to check if the form fields are empty.
=> Form fixes hacktoberfest2021

Binary-Search/binary search.php
added binary search method using php
=> Create binary search.php

Linear Search/linear search.cpp
=> Create linear search.cpp

Chess Game/Chess Game.js, Clock/script.js, Clock_v2/clock.js, Converter/app.js, Stopwatch/index.html, Stopwatch/index.js, Stopwatch/style.css, Stopwatch/style.scss, currency-convertor/app.js
Added **Stopwatch** using **vanilla js**, **HTML** and **Sass**
=> Added Stopwatch

SlidingImages/index.html, SlidingImages/script.js, SlidingImages/style.css
This is my first contribution.
I made this mini-project with vanilla HTML, CSS, and JS.
Also, this is my first Hacktoberfest so I hope this will be good enough.
=> Images Slider

Tik Tak Toe/script.js
Style Improvements and arrow functions to replace functions for the Tic Tac Toe Implementation
=> ES6 Refactoring For TTT

Speed-Typer/index.html, Speed-Typer/readme.md, Speed-Typer/script.js, Speed-Typer/style.css
=> Typing gameJS

Hover-Effect-on-website-Icons/index.html, Hover-Effect-on-website-Icons/style.css
Added hover effect on social media icons. so codes can be reused by other developers.
=> added social media icons hover effect Html and CSS files

Recipe search APP/index.html, Recipe search APP/main.js, Recipe search APP/style.css
Hello @rahulray11 can you merge my pull request? I have added a web app i have developed using the Edamam API which is fully responsive.
would appreciate so much.
Thank you.
=> initial commit for Recipe search app

Music Player/musicplayer.py
Python Music Player app made using Tkinter 
Tkinter is Python's de-facto standard GUI (Graphical User Interface) package.
Consider this as a part of Hacktober Fest 2021 (GVP)
Thank you.
=> Music Player app in Python

node-rest-apis/app.js, node-rest-apis/config/connection.js, node-rest-apis/model/user.js, node-rest-apis/package.json, node-rest-apis/readme.md
Hi there,
I have created crud rest apis using node js mysql2 express. Hope it will be helpful for community members.
Thanks and keep the good work up  🙏
=> Added Node Js RestApis CRUD operations

Automated Bot For Chrome's Dino Game.py
Created a python script which can automatically play the chrome's dinosaur game and reach the highest level by its own.
=> Create Automated Bot For Chrome's Dino Game.py

Data Structure/DEQUEUE.cpp, Data Structure/circuler_queue.cpp, Data Structure/priority_queue.cpp, Data Structure/queue.cpp, Data Structure/sorting/bubble_sort.cpp, Data Structure/sorting/insertion_sort.cpp, Data Structure/sorting/quick_sort.cpp, Data Structure/sorting/selection_sort.cpp, Data Structure/stack.cpp
hi there,
I'm adding Data Structure programs in Data structure folder.
4 sorting techniques added.
1) bubble_sort.cpp
2) insersion_sort.cpp
3) quick_sort.cpp
4) selection_sort.cpp
Also added
5) stack.cpp
6) queue.cpp
7) priority_queue.cpp
8) circuler_queue.cpp
9) DEQUEUE.cpp
=> Data structure programs added

Typing Game/index.html, Typing Game/script.js, Typing Game/style.css
plz merge it and give hacktoberfest accepted tag.
=> Typing Game 
